vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set scrolloff=6")
vim.g.mapleader = " "
vim.cmd("noremap <C-h> <C-w>h")
vim.cmd("noremap <C-j> <C-w>j")
vim.cmd("noremap <C-k> <C-w>k")
vim.cmd("noremap <C-l> <C-w>l")
vim.cmd("inoremap jk <ESC>")
vim.cmd("inoremap kj <ESC>")

vim.cmd('inoremap " ""<left>')
vim.cmd("inoremap ' ''<left>")
vim.cmd("inoremap ( ()<left>")
vim.cmd("inoremap [ []<left>")
vim.cmd("inoremap { {}<left>")
vim.cmd("inoremap {<CR> {<CR>}<ESC>O")
vim.cmd("inoremap {;<CR> {<CR>};<ESC>O")
vim.cmd("noremap <leader>t :sp +term<CR><C-w>J")
vim.cmd("tnoremap <ESC><ESC> <C-\\><C-N>")
vim.cmd("imap <C-H> <C-W>")
